import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: ReactNode
}>): JSX.Element {
  return (
    <html suppressHydrationWarning lang='en'>
      <body suppressHydrationWarning className={quicksand.className}>{children}</body>
    </html>
  )
}
